### ISSUE TITLE
Add CLI flags to shacl_validate.py to run certain validations

### ISSUE THREAD

**Issue by wgwz** [regen-network/regen-registry-standards#25]
Currently the `shacl_validate.py` script runs all validations for credit classes, credit batches and projects every time it is run. We would like to be able to run only specific validations like so:

```
./shacl_validate.py --credit-classes --credit-batches --projects
```

```
./shacl_validate.py --credit-classes --credit-batches
```

```
./shacl_validate.py --credit-batches
```

Ideally, we would just make use of python's built-in argparse library for this, since it would be nice not to have to install any python dependencies.

**Comment by wgwz** [comment]
The default behavior of the script should be maintained, when we do the following, it should just run all validations:

```
./shacl_validate.py
```

**Comment by S4mmyb** [comment]
I think using argparse for this in the future would be nice! I did a bit of this last year in the s2-ard repo if we want to use it as a model -> https://github.com/regen-network/regen-s2-ard/blob/384359299360115411380d67ed45698710156a68/src/ard.py#L422
