### ISSUE TITLE
Add support for storing impact/co-benefits and sdgs related info in anchored metadata

### ISSUE THREAD

**Issue by blushi** [regen-network/regen-registry-standards#63]
Currently we store the impact info for a credit class in the off-chain `credit_class_version.metadata`.

We should update that to be stored in the anchored/on-chain class metadata instead and add the ability to distinguish measured co-benefits from project co-benefit (https://github.com/regen-network/rnd-dev-team/issues/1740).

We should also include project-specific impact description in the anchored project metadata (https://github.com/regen-network/rnd-dev-team/issues/1738).

**Comment by blushi** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/regen-registry-standards/63?planning-poker) with Zenhub @wgwz

**Comment by ryanchristo** [comment]
Marking as blocked as the pull request is waiting on the actual data before proceeding.
